# Starter pipeline
# Pull from Repo
# Import Project into Docekr SOAtest CLI container and Run
# Azure YAML docs:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

# Set Up Project
steps:
- script: |
    echo "Starting Pipeline Execution."
    echo "Create ./temp directory for volume mount."
    mkdir temp
    echo ${PWD}
    echo "Copy SOAtest project contents to volume directory."
    cp -R $(soatest.project) temp/.
    
    # Set Up and write .properties file
    echo  -e "\n~~~\nSetting up and creating soatestcli.properties file.\n"
    echo $"
    dtp.url=$(license.server.url)
    dtp.user=admin
    dtp.password=$(license.server.password)
    dtp.share.enabled=true
    dtp.project=ADO_1
    report.dtp.publish=true
    techsupport.advanced=false
    techsupport.auto_creation=true
    techsupport.item.environment=true
    techsupport.item.general=true
    techsupport.archive_location=/temp
    techsupport.send_email=false
    techsupport.verbose=true
    techsupport.verbose.scontrol=false
    license.network.auth.enabled=true  
    license.network.password=$(license.server.password)
    license.network.url=$(license.server.url)
    license.network.use.specified.server=true
    license.network.user=admin
    jtest.license.network.edition=custom_edition
    jtest.license.custom_edition_features=Jtest, Static Analysis, Flow Analysis, OWASP Rules, CWE Rules, PCI DSS Rules, DISA STIG Rules, Security Rules, Automation, Desktop Command Line, DTP Publish, Coverage, Unit Test, Unit Test Bulk Creation, Unit Test Tier 1, Unit Test Tier 2, Unit Test Tier 3, Unit Test Tier 4, Unit Test Spring Framework, Change Based Testing
    virtualize.license.use_network=true" >> temp/soatestcli.properties
    echo -e "\nDebug -- Verify workspace contents.\n"
    ls -R
    echo -e "\nDebug -- Verify soatestcli.properties file contents."
    cat temp/soatestcli.properties

    # Run Docker container with mount and run tests
    echo -e "\n~~~\nRun SOAtestCLI Docker container & mount ./temp volume.\n"
    
    docker --version

    docker run -i \
    -e ACCEPT_EULA=true \
    -v /home/jtest/jtest/examples/demo:$PWD \
    lavanya93/jtest:2022.1.0 /bin/bash -c " \
    /home/jtest/jtest/jtestcli \
    -data /home/jtest/jtest/examples/demo/demo.data.json \
    -config 'jtest.dtp://Recommended Rules' \
    -local settings temp/soatestcli.properties \
    -publish \
    -report /temp" \
    docker ps \
    echo -e "\nDebug -- Verify ./temp contents\n"
    ls -R $(pwd)/temp
  displayName: Run Tests
  env:
    pwd: $(Build.Repository.LocalPath)
  
- publish: /home/vsts/work/1/s/temp
  artifact: TSA
# Publish Test Results

- task: PublishParasoftTestResults@1
  
  displayName: Publish SOAtest Test Results
  inputs:
    testRunner: 'SOAtest9x'
    testResultsFiles: '$(Build.Repository.LocalPath)/temp/rep*.xml'
# docker cp $(System.DefaultWorkingDirectory) ctp20212-ltc-cam-1:/tmp/root/parasoft/techsupport/