# Starter pipeline
# Pull from Repo
# Import Project into Docekr SOAtest CLI container and Run
# Azure YAML docs:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

# Set Up Project
steps:
- script: |
    echo "Starting Pipeline Execution."
    echo "Create ./temp directory for volume mount."
    mkdir temp
    echo ${PWD}
    echo "Copy SOAtest project contents to volume directory."
    cp -R $(soatest.project) temp/.
    
    # Set Up and write .properties file
    echo  -e "\n~~~\nSetting up and creating soatestcli.properties file.\n"
    echo $"
    parasoft.eula.accepted=true
    dtp.url=$(license.server.url)
    dtp.user=admin
    dtp.password=$(license.server.password)
    dtp.share.enabled=true
    dtp.project=ADO_1
    console.verbosity.level=high
    report.dtp.publish=true
    techsupport.create.on.exit=true
    techsupport.enabled=true
    techsupport.include.reports=true
    techsupport.include.sources=true
    techsupport.verbose.scontrol=false
    jtest.license.use_network=true
    jtest.license.network.edition=custom_edition
    jtest.license.custom_edition_features=Jtest, Static Analysis, Flow Analysis, OWASP Rules, CWE Rules, PCI DSS Rules, DISA STIG Rules, Security Rules, Automation, Desktop Command Line, DTP Publish, Coverage, Unit Test, Unit Test Bulk Creation, Unit Test Tier 1, Unit Test Tier 2, Unit Test Tier 3, Unit Test Tier 4, Unit Test Spring Framework, Change Based Testing" >> temp/soatestcli.properties
    echo -e "\nDebug -- Verify workspace contents.\n"
    ls -R
    echo -e "\nDebug -- Verify soatestcli.properties file contents."
    cat temp/soatestcli.properties

    # Run Docker container with mount and run tests
    echo -e "\n~~~\nRun SOAtestCLI Docker container & mount ./temp volume.\n"
    
    docker --version

    docker run -i \
    -e ACCEPT_EULA=true \
    -v $PWD:$PWD \
    -v $PWD:/root/.m2 \
    lavanya93/jtest:2022.1.0 /bin/bash -c " \
    ./gradlew clean jtest-agent test jtest -Djtest.config="builtin://Unit Tests" \
    docker ps \
    echo -e "\nDebug -- Verify ./temp contents\n"
    ls -R $(pwd)/temp
  displayName: Run Tests
  env:
    pwd: $(Build.Repository.LocalPath)
  
- publish: /home/vsts/work/1/s/temp
  artifact: TSA
# Publish Test Results

- task: PublishParasoftTestResults@1
  
  displayName: Publish SOAtest Test Results
  inputs:
    testRunner: 'SOAtest9x'
    testResultsFiles: '$(Build.Repository.LocalPath)/temp/rep*.xml'
# docker cp $(System.DefaultWorkingDirectory) ctp20212-ltc-cam-1:/tmp/root/parasoft/techsupport/